openapi: 3.0.0
info:
  title: PersonaTalk
  description: The backend API for communicating with digital personas
  version: 1.0.0

paths:
  /v1/agent:
    get:
      tags:
        - Agent
      summary: Get all agents' information
      responses:
        "200":
          description: HTTP 200 OK - Successfully returned agents' information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Agent"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "404":
          $ref: "#/components/responses/404AgentError"
        "500":
          $ref: "#/components/responses/500Error"

    post:
      tags:
        - Agent
      summary: Create a new agent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Agent"
        example:
          agent_name: Jasmine
          description: A personal assistant for-
          persona: Jasmine is a-
          model: gpt-3.5-turbo-0613
      responses:
        "201":
          description: HTTP 201 Created - Agent created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Agent"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

    delete:
      tags:
        - Agent
      summary: Delete all agents
      responses:
        "204":
          $ref: "#/components/responses/204Success"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

  /v1/agent/{agent_name}:
    get:
      tags:
        - Agent
      summary: Get specified agent's information
      parameters:
        - name: agent_name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: HTTP 200 OK - Successfully returned agent information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Agent"
          example:
            agent_name: Jasmine
            description: A personal assistant for-
            persona: Jasmine is a-
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "404":
          $ref: "#/components/responses/404AgentError"
        "500":
          $ref: "#/components/responses/500Error"

    delete:
      tags:
        - Agent
      summary: Delete specified agent
      parameters:
        - name: agent_name
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          $ref: "#/components/responses/204Success"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "404":
          $ref: "#/components/responses/404AgentError"
        "500":
          $ref: "#/components/responses/500Error"

  /v1/user:
    get:
      tags:
        - User
      summary: Get all users' information
      responses:
        "200":
          description: HTTP 200 - Successfully returned users' information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "404":
          $ref: "#/components/responses/404UserError"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

    delete:
      tags:
        - User
      summary: Delete all users
      responses:
        "204":
          $ref: "#/components/responses/204Success"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

  /v1/user/{username}:
    get:
      tags:
        - Agent
      summary: Get specified user's information
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: HTTP 200 - Successfully returned user information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          example:
            username: cozy
            password: adh9na8dy98andy98
            display_name: Chris
        "404":
          $ref: "#/components/responses/404UserError"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

    delete:
      tags:
        - User
      summary: Delete specified user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          $ref: "#/components/responses/204Success"
        "404":
          $ref: "#/components/responses/404UserError"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

  /v1/conversation:
    get:
      tags:
        - Conversation
      summary: Get all conversations
      responses:
        "200":
          description: HTTP 200 OK - Successfully returned all conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Conversation"
        "404":
          $ref: "#/components/responses/404ConversationError"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

    delete:
      tags:
        - Conversation
      summary: Delete all conversations
      responses:
        "204":
          $ref: "#/components/responses/204Success"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"
  
  /v1/conversation/{username}:
    get:
      tags:
        - Conversation
      summary: Get all conversation for the specified user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: HTTP 200 OK - Successfully returned all user's conversations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Conversation"
        "404":
          $ref: "#/components/responses/404ConversationError"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

    delete:
      tags:
        - Conversation
      summary: Delete all conversations for the specified user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          $ref: "#/components/responses/204Success"
        "404":
          $ref: "#/components/responses/404ConversationError"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

  /v1/conversation/{username}/{agent_name}:
    get:
      tags:
        - Conversation
      summary: Get conversation between the specified user and agent
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: agent_name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: HTTP 200 OK - Successfully returned specified conversation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Conversation"
        "404":
          $ref: "#/components/responses/404ConversationError"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

    delete:
      tags:
        - Conversation
      summary: Delete specified conversation
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
        - name: agent_name
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          $ref: "#/components/responses/204Success"
        "404":
          $ref: "#/components/responses/404ConversationError"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

  /v1/chat/completion:
    post:
      tags:
        - Chat
      summary: Create a response for the given message using conversation history
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
            example:
              username: cozy
              agent_name: Jasmine
              message: hi
      responses:
        "200":
          description: HTTP 200 OK - Response generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        "404":
          $ref: "#/components/responses/404UserError"
        "404":
          $ref: "#/components/responses/404AgentError"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

  /v1/auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
        example:
          username: alice
          password: alice123
          display_name: Alice
      responses:
        "201":
          description: HTTP 201 - User registered successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "500":
          $ref: "#/components/responses/500Error"

  /v1/auth/login:
    post:
      tags:
        - Auth
      summary: Log in an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
        example:
          username: alice
          password: alice123
      responses:
        "200":
          description: HTTP 200 OK - User logged in successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "500":
          $ref: "#/components/responses/500Error"

  /v1/auth/logout:
    get:
      tags:
        - Auth
      summary: Log out the current user
      responses:
        "204":
          $ref: "#/components/responses/204Success"
        "401":
          $ref: "#/components/responses/401UnauthorizedError"
        "500":
          $ref: "#/components/responses/500Error"

  /v1/auth/current:
    get:
      tags:
        - Auth
      summary: Reply with the currently authenticated user
      responses:
        "200":
          description: HTTP 200 OK - Currently authenticated user returned successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "500":
          $ref: "#/components/responses/500Error"

components:
  schemas:
    Agent:
      type: object
      properties:
        agent_name:
          type: string
        description:
          type: string
        persona:
          type: string

    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        display_name:
          type: string

    Message:
      type: object
      properties:
        username:
          type: string
        agent_name:
          type: string
        message:
          type: string

    Response:
      type: object
      properties:
        response_id:
          type: int
        username:
          type: string
        agent_name:
          type: string
        initial_message:
          type: string
        message_reply:
          type: string
        timestamp:
          type: string
          format: date-time

  responses:
    204Success:
      description: HTTP 204 - No content to return
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    400Error:
      description: HTTP 400 - Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    404UserError:
      description: HTTP 404 - User(s) not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    404AgentError:
      description: HTTP 404 - Agent(s) not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    404ConversationError:
      description: HTTP 404 - Conversation(s) not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    401UnauthorizedError:
      description: HTTP 401 - Unauthorized to access resource
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    403Error:
      description: HTTP 403 - Forbidden to access resource
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    500Error:
      description: HTTP 500 - Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

  x-rate-limits:
    description: Rate limiting is applied to prevent abuse of the API. Requests beyond the rate limit will receive a '429 Too Many Requests' response.
    headers:
      X-RateLimit-Limit:
        description: The maximum number of requests allowed within the rate limit window.
      X-RateLimit-Remaining:
        description: The number of remaining requests within the current rate limit window.
      X-RateLimit-Reset:
        description: The time at which the rate limit window will reset.
    global:
      rateLimit: 10
      rateLimitPeriod: minute

tags:
  - name: Agent
    description: Operations related to the agent
  - name: User
    description: Operations related to the user
  - name: Conversation
    description: Operations related to conversation
  - name: Chat
    description: Operations related to communicating with user
